### PR TITLE
Don't run docker puller on nodes where px doesn't run

### LINKED ISSUE #45: Docker puller during PX upgrade should not pull from nodes that has px/enabled=false
**BUG REPORT **: When PX upgrades, there is a docker puller daemonset that pulls PX image on all nodes. That should skip nodes which has `px/enabled=false` as PX doesn't run there. So that would be an unnecessary pull.

### PR DESCRIPTION
**Pull request by harsh-px**
Fixes #45

Signed-off-by: Harsh Desai <harsh@portworx.com>

### CODE REVIEW

File: pkg/cluster/px/px.go [hunk 1]
```diff
@@ -345,6 +346,27 @@ func (ops *pxClusterOps) runDockerPuller(imageToPull string) error {
...
 				Spec: corev1.PodSpec{
+					Affinity: &corev1.Affinity{
+						NodeAffinity: &corev1.NodeAffinity{
+							RequiredDuringSchedulingIgnoredDuringExecution: &corev1.NodeSelector{
+								NodeSelectorTerms: []corev1.NodeSelectorTerm{
+									{
+										MatchExpressions: []corev1.NodeSelectorRequirement{
+											{
+												Key:      pxEnableLabelKey,
+												Operator: corev1.NodeSelectorOpNotIn,
```
Comment (adityadani) [inline pkg/cluster/px/px.go]: Dont we have other "non" true values like uninstall/remove?

Comment (harsh-px) [reply pkg/cluster/px/px.go]: `px/enabled=remove` eventually uses `px/enabled=false` as a way to prevent px from running on the node.

`px/enabled=remove` is a super set operation. When applied, oci-monitor stops PX systemd service and then applies the `px/enabled=false` label on the node.

Comment (adityadani) [reply pkg/cluster/px/px.go]: Is it same for `px/enabled=uninstall` as well?

Comment (harsh-px) [reply pkg/cluster/px/px.go]: We don't have the uninstall switch. `px/enabled=remove` is the switch that does the uninstall.

**Comment by harsh-px** [comment]
golint failing due to https://github.com/Azure/acr-builder/pull/114
