### PR TITLE
scale down shared applications only for 1.2 to 1.3 upgrade

### LINKED ISSUE #22: Scale down shared applications only if upgrading from 1.2 to 1.3
**BUG REPORT**: Current logic will scale down shared applications regardless of the start and end version. This should only happen if start = 1.2.X and end = 1.3.X

### PR DESCRIPTION
**Pull request by harsh-px**
Fixes #22

Signed-off-by: Harsh Desai <harsh@portworx.com>

### CODE REVIEW

**Comment by harsh-px** [comment]
Vendoring issues due to logrus
```
01:04 $ dep ensure
Solving failure: No versions of go.pedge.io/dlog met constraints:
	master: Could not introduce go.pedge.io/dlog@master due to a case-only variation: it depends on "github.com/Sirupsen/logrus", but "github.com/sirupsen/logrus" was already established as the case variant for that project root by the following other dependers:
	(root)
	github.com/libopenstorage/gossip@logrus
	github.com/portworx/sched-ops@snapshot
```
Will reopen once fixed.

**Comment by adityadani** [comment]
Why only stop shared volume apps when migrating from 1.2 to 1.3? I think there should a command line flag to decide that, so if 1.3.x releases have any module changes then we can still stop applications without needing a change in talisman code.

**Comment by harsh-px** [comment]
> Why only stop shared volume apps when migrating from 1.2 to 1.3? I think there should a command line flag to decide that, so if 1.3.x releases have any module changes then we can still stop applications without needing a change in talisman code.

Add an explicit flag in incremental to choose whether or not to scale down shared apps.

If the flag is not specified, the default will be to check 1.2 => 1.3 upgrade. Want to keep that as default as callers may not know the requirement and we need to protect against that.

File: cmd/talisman/talisman.go [hunk 1]
```diff
@@ -75,4 +82,7 @@ func init() {
 	flag.StringVar(&newPXTag, "pxtag", "", "(optional) New Portworx tag to use for the upgrade")
 	flag.StringVar(&kubeconfig, "kubeconfig", "", "(optional) Absolute path of the kubeconfig file")
 	flag.StringVar(&dockerRegistrySecret, "dockerregsecret", "", "(optional) Kubernetes Secret to pull docker images from a private registry")
+	flag.StringVar(&sharedAppsScaleDown, "scaledownsharedapps", string(px.SharedAppsScaleDownAuto),
+		fmt.Sprintf("(optional) instructs scale down behavior of px shared apps. Supported values: %s, %s, %s",
```
Comment (lpabon) [inline cmd/talisman/talisman.go]: May want more text here explaining. This is confusing for those not used to px. Also, may want to spell out Portworx instead of just using `px`.

File: pkg/cluster/px/px.go [hunk 2]
```diff
@@ -57,14 +75,19 @@ const (
...
+
 // Cluster an interface to manage a storage cluster
 type Cluster interface {
 	// Create creates the given cluster
 	Create(c *apiv1alpha1.Cluster) error
 	// Status returns the current status of the given cluster
 	Status(c *apiv1alpha1.Cluster) (*apiv1alpha1.ClusterStatus, error)
 	// Upgrade upgrades the given cluster
-	Upgrade(c *apiv1alpha1.Cluster) error
+	Upgrade(c *apiv1alpha1.Cluster, opts *UpgradeOptions) error
```
Comment (lpabon) [inline pkg/cluster/px/px.go]: Nice. I like this.

File: pkg/cluster/px/px.go [hunk 3]
```diff
@@ -39,12 +54,15 @@ const (
 	pxdRestPort        = 9001
 	pxServiceName      = "portworx-service"
 	pxClusterRoleName  = "node-get-put-list-role"
+	pxVersionLabel     = "PX Version"
```
Comment (lpabon) [inline pkg/cluster/px/px.go]: could this string be more kubernetes-like? Like px-version, or something like that? Just a suggestion

Comment (harsh-px) [reply pkg/cluster/px/px.go]: This label is populated by Portworx (porx) on the node labels. We simply read it here.

File: cmd/talisman/talisman.go (hunk 1 above)
Comment (harsh-px) [reply cmd/talisman/talisman.go]: In incremental, updated text to 

```
  -scaledownsharedapps string
    	(optional) instructs scale down behavior of Portworx shared apps. Supported values:
	auto: During the upgrade process, Portworx shared applications will be scaled down to 0 replicas if 1.2 to 1.3 version upgrade is detected.
	on: During the upgrade process, Portworx shared applications will be unconditionally scaled down to 0 replicas.
	off: Upgrade process will not scale down Portworx shared applications. (default "auto")
```
